# Generated by Django 5.0 on 2023-12-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('batch', models.IntegerField(choices=[(1, '6-7 AM'), (2, '7-8 AM'), (3, '8-9 AM'), (4, '5-6 PM')])),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.payment')),
            ],
        ),
    ]
